server {
    listen 80;
    server_name _; 

    # 1. ESTILOS Y MEDIA DIRECTOS (Prioridad Máxima)
    location /static/ {
        alias /usr/share/nginx/html/static/;
        include /etc/nginx/mime.types;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /usr/share/nginx/html/media/;
    }

    # 2. BACKEND API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. BACKEND ADMIN (Sin barra final)
    location /admin {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 4. WEBSOCKETS
    location /ws/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # 5. FRONTEND REACT (Red de seguridad, siempre al final)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}