# Generated by Django 5.2.12 on 2026-04-03 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modulo_kds', models.BooleanField(default=False, help_text='¿Tiene pantalla de cocina?')),
                ('modulo_inventario', models.BooleanField(default=False)),
                ('modulo_delivery', models.BooleanField(default=False)),
                ('max_sedes', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_o_nombre', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField(default=2)),
                ('mesa_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_unidas', to='negocios.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fin_prueba', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('mod_cocina_activo', models.BooleanField(default=False)),
                ('mod_inventario_activo', models.BooleanField(default=False)),
                ('mod_analiticas_activo', models.BooleanField(default=False)),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salon', 'En Salón'), ('llevar', 'Para Llevar'), ('delivery', 'Delivery')], default='salon', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'En Cocina'), ('listo', 'Listo para entregar'), ('pagado', 'Pagado y Cerrado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta (Visa/MC)'), ('yape_plin', 'Yape / Plin')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='negocios.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('tiene_variaciones', models.BooleanField(default=False)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='negocios.negocio')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.sede'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.sede'),
        ),
        migrations.CreateModel(
            name='VariacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='negocios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('notas_y_modificadores', models.JSONField(blank=True, default=dict)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='negocios.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.producto')),
                ('variacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='negocios.variacionproducto')),
            ],
        ),
    ]
