# Generated by Django 5.2.12 on 2026-04-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
