# Generated by Django 5.2.12 on 2026-04-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_orden_cliente_nombre_orden_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='pago_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'En Cocina'), ('listo', 'Listo para entregar'), ('pagado', 'Pagado y Cerrado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
