# Generated by Django 5.2.12 on 2026-04-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_orden_cancelado_orden_motivo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_venta_rapida',
            field=models.BooleanField(default=False),
        ),
    ]
