# Generated by Django 5.2.12 on 2026-04-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_producto_es_venta_rapida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='variacion',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='notas_cocina',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_seleccion',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GrupoVariacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('obligatorio', models.BooleanField(default=True)),
                ('seleccion_multiple', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_variacion', to='negocios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ModificadorRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionVariacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='negocios.grupovariacion')),
            ],
        ),
    ]
