# Generated by Django 5.2.12 on 2026-04-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_remove_detalleorden_variacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('puede_cobrar', models.BooleanField(default=False)),
                ('puede_configurar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=4, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.rol')),
            ],
        ),
    ]
