# Generated by Django 5.2.12 on 2026-04-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_rol_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='negocios.sede'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pin',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='negocios.rol'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('pin', 'negocio')},
        ),
    ]
