# Generated by Django 5.2.12 on 2026-04-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0007_empleado_negocio_empleado_sede_alter_empleado_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('fondo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='abierta', max_length=20)),
                ('empleado_abre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.empleado')),
            ],
        ),
    ]
