# Generated by Django 5.2.12 on 2026-04-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0008_sesioncaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='empleado_cierra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres', to='negocios.empleado'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='hora_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negocios.sede'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='ventas_digitales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='ventas_efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sesioncaja',
            name='empleado_abre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas', to='negocios.empleado'),
        ),
    ]
