# Generated by Django 5.2.12 on 2026-04-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0009_sesioncaja_empleado_cierra_sesioncaja_hora_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='declarado_efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='declarado_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='declarado_yape',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='esperado_digital',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='esperado_efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
