# Generated by Django 5.2.12 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0010_sesioncaja_declarado_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='mod_delivery_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='numero_yape',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
