# Generated by Django 5.2.12 on 2026-04-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0011_negocio_mod_delivery_activo_negocio_numero_yape'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_adicional_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cancelado',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='pago_confirmado',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Por Cobrar'), ('pagado', 'Pagado Completamente'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='sesion_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='negocios.sesioncaja'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pin',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='opcionvariacion',
            name='precio_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'En Cocina'), ('listo', 'Listo para entregar'), ('completado', 'Entregado / Mesa Cerrada'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variacionproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('sede', 'numero_o_nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('negocio', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='sede',
            unique_together={('negocio', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['sede', 'estado'], name='negocios_or_sede_id_e53660_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['creado_en'], name='negocios_or_creado__a6b9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['sede', 'estado_pago'], name='negocios_or_sede_id_081dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['negocio', 'disponible'], name='negocios_pr_negocio_1a9164_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('sede',), name='unica_caja_abierta_por_sede'),
        ),
        migrations.AddField(
            model_name='detalleordenopcion',
            name='detalle_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_seleccionadas', to='negocios.detalleorden'),
        ),
        migrations.AddField(
            model_name='detalleordenopcion',
            name='opcion_variacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.opcionvariacion'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='negocio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.plansaas'),
        ),
    ]
