# Generated by Django 5.2.12 on 2026-04-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0012_detalleordenopcion_suscripcion_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['sesion_caja', 'fecha_pago'], name='negocios_pa_sesion__1dfabe_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['orden'], name='negocios_pa_orden_i_1963e4_idx'),
        ),
    ]
