# Generated by Django 5.2.12 on 2026-04-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0014_categoria_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso (Base/Ajuste)'), ('egreso', 'Egreso (Gasto/Retiro)')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to='negocios.empleado')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='negocios.sede')),
                ('sesion_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='negocios.sesioncaja')),
            ],
            options={
                'indexes': [models.Index(fields=['sesion_caja', 'tipo'], name='negocios_mo_sesion__11f1d3_idx')],
            },
        ),
    ]
