# Generated by Django 5.2.12 on 2026-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0015_movimientocaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='mod_analiticas_activo',
        ),
        migrations.AddField(
            model_name='negocio',
            name='color_primario',
            field=models.CharField(default='#ff5a1f', max_length=7),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mod_clientes_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mod_facturacion_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mod_salon_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='tema_fondo',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
