# Generated by Django 5.2.12 on 2026-04-13 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0016_remove_negocio_mod_analiticas_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='mod_bot_wsp_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mod_carta_qr_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mod_ml_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='negocios.plansaas'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='modulo_bot_wsp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='modulo_carta_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='modulo_ml',
            field=models.BooleanField(default=False),
        ),
    ]
