# Generated by Django 5.2.12 on 2026-04-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0017_negocio_mod_bot_wsp_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('circular', 'Circular'), ('cuadrada', 'Cuadrada')], default='cuadrada', max_length=20),
        ),
        migrations.AddField(
            model_name='mesa',
            name='posicion_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesa',
            name='posicion_y',
            field=models.IntegerField(default=0),
        ),
    ]
