# Generated by Django 5.2.12 on 2026-04-17 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0019_insumo_recetadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('unidades', 'Unidades')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='insumos/')),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_insumos', to='negocios.negocio')),
            ],
        ),
        migrations.AlterField(
            model_name='recetadetalle',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.insumobase'),
        ),
        migrations.CreateModel(
            name='InsumoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insumo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_locales', to='negocios.insumobase')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='negocios.sede')),
            ],
            options={
                'unique_together': {('insumo_base', 'sede')},
            },
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
    ]
