# Generated by Django 5.2.12 on 2026-04-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0020_insumobase_alter_recetadetalle_insumo_insumosede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumosede',
            name='stock_general',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
