# Generated by Django 5.2.12 on 2026-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0021_insumosede_stock_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumosede',
            name='stock_general',
        ),
        migrations.AddField(
            model_name='insumobase',
            name='stock_general',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
