# Generated by Django 5.2.12 on 2026-04-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0022_remove_insumosede_stock_general_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=3, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.insumobase')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='negocios.opcionvariacion')),
            ],
        ),
    ]
