# Generated by Django 5.2.12 on 2026-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0023_recetaopcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('yape', 'Yape'), ('plin', 'Plin')], max_length=20, null=True),
        ),
    ]
