# Generated by Django 5.2.12 on 2026-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0024_orden_metodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='metodo',
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta (Visa/MC)'), ('yape', 'Yape'), ('plin', 'Plin')], max_length=20),
        ),
    ]
