# Generated by Django 5.2.12 on 2026-04-19 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0025_remove_orden_metodo_alter_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='mesero',
            field=models.ForeignKey(blank=True, help_text='¿Quién tomó el pedido inicial?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_tomadas', to='negocios.empleado'),
        ),
        migrations.AddField(
            model_name='orden',
            name='sesion_caja',
            field=models.ForeignKey(blank=True, help_text='Turno en el que se cobró', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='negocios.sesioncaja'),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_nombre', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('anular_plato', 'Anulación de Plato en Cocina'), ('cancelar_orden', 'Orden Completa Cancelada'), ('descuento', 'Descuento Aplicado Manualmente'), ('modificar_caja', 'Modificación de Caja Fuerte')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.empleado')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.orden')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='negocios.sede')),
            ],
            options={
                'indexes': [models.Index(fields=['sede', 'fecha'], name='negocios_re_sede_id_3e1eb9_idx'), models.Index(fields=['accion'], name='negocios_re_accion_b466d7_idx')],
            },
        ),
    ]
