# Generated by Django 5.2.12 on 2026-04-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0026_orden_mesero_orden_sesion_caja_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='columnas_salon',
            field=models.IntegerField(default=2),
        ),
    ]
