# Generated by Django 5.2.12 on 2026-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0027_sede_columnas_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificadorrapido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
