# Generated by Django 5.2.12 on 2026-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0028_modificadorrapido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificadorrapido',
            name='categorias_aplicables',
            field=models.ManyToManyField(blank=True, related_name='modificadores_rapidos', to='negocios.categoria'),
        ),
    ]
