# Generated by Django 5.2.12 on 2026-04-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0029_modificadorrapido_categorias_aplicables'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacar_como_promocion',
            field=models.BooleanField(default=False, help_text='¿Aparece destacado en el Bot de WhatsApp o Carta QR?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_combo',
            field=models.BooleanField(default=False, help_text='Indica si este producto está compuesto por otros productos'),
        ),
        migrations.CreateModel(
            name='ComponenteCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_combo', to='negocios.producto')),
                ('producto_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='negocios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CuponPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_porcentaje', models.BooleanField(default=False)),
                ('limite_usos', models.IntegerField(default=1)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioVisibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_permitidos', models.JSONField(default=list)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('mensaje_fuera_horario', models.CharField(default='Disponible otros días', max_length=100)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='negocios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recargo_llevar', 'Recargo por empaque (Llevar)'), ('delivery_gratis', 'Delivery Gratis por Monto'), ('descuento_dia', 'Descuento por Día Específico')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_porcentaje', models.BooleanField(default=False)),
                ('monto_minimo_orden', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedido_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('distritos_cobertura', models.TextField(help_text='Lista de distritos o barrios separados por comas')),
                ('activa', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_delivery', to='negocios.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad_pedidos', models.IntegerField(default=0)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='negocios.negocio')),
            ],
            options={
                'unique_together': {('negocio', 'telefono')},
            },
        ),
    ]
