# Generated by Django 5.2.12 on 2026-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0030_producto_destacar_como_promocion_producto_es_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
