# Generated by Django 5.2.12 on 2026-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0031_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='whatsapp_instancia',
            field=models.CharField(blank=True, help_text='Nombre exacto de la instancia en Evolution API (Ej: brava_ventanilla)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Número de teléfono del bot para esta sede', max_length=20, null=True),
        ),
    ]
