# Generated by Django 5.2.12 on 2026-04-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0032_sede_whatsapp_instancia_sede_whatsapp_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_pago_esperado',
            field=models.CharField(blank=True, help_text='Ej: Yape, Efectivo (con vuelto de S/50)', max_length=50, null=True),
        ),
    ]
