# Generated by Django 5.2.12 on 2026-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0033_orden_costo_envio_orden_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='pago_validado_bot',
            field=models.BooleanField(default=False, help_text='¿Gemini validó la captura?'),
        ),
    ]
