# Generated by Django 5.2.12 on 2026-04-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0034_orden_pago_validado_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bot_estado',
            field=models.CharField(default='INICIO', help_text='Estado actual: INICIO, ESPERANDO_PAGO, ESPERANDO_UBICACION, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bot_memoria',
            field=models.JSONField(blank=True, default=dict, help_text='Guarda el carrito temporal, coordenadas y datos de la sesión actual.'),
        ),
    ]
