# Generated by Django 5.2.12 on 2026-04-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0035_cliente_bot_estado_cliente_bot_memoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonadelivery',
            name='distritos_cobertura',
        ),
        migrations.AddField(
            model_name='sede',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud del local', null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud del local', null=True),
        ),
        migrations.AddField(
            model_name='zonadelivery',
            name='radio_max_km',
            field=models.FloatField(default=2.0, help_text='Radio máximo en kilómetros para esta tarifa'),
        ),
    ]
