# Generated by Django 5.2.12 on 2026-04-28 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0036_remove_zonadelivery_distritos_cobertura_sede_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, help_text='Pega el Plus Code de Google Maps (Ej: 6MC5+QQ Ventanilla)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Se autocompleta al guardar', null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Se autocompleta al guardar', null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='whatsapp_instancia',
            field=models.CharField(blank=True, help_text='Nombre exacto en Evolution API', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Número del bot', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PromocionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cumpleanos', 'Felicitación de Cumpleaños'), ('inactivo_15d', 'Cliente inactivo por 15 días'), ('vip', 'Oferta exclusiva para clientes VIP')], max_length=50)),
                ('mensaje_gancho', models.TextField(help_text='Ej: ¡Feliz cumple {nombre}! Usa el código {cupon} para un 20% de dscto.')),
                ('activa', models.BooleanField(default=True)),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.cuponpromocional')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_bot', to='negocios.sede')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('saludo', 'Mensaje de Bienvenida (Primer contacto)'), ('fuera_horario', 'Mensaje de Fuera de Horario'), ('despedida', 'Despedida tras compra exitosa'), ('espera', 'Mensaje de espera (Cuando hay alta demanda)')], max_length=50)),
                ('mensaje', models.TextField(help_text='Usa {nombre} para que el bot diga el nombre del cliente.')),
                ('activa', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_bot', to='negocios.sede')),
            ],
            options={
                'unique_together': {('sede', 'trigger')},
            },
        ),
    ]
