# Generated by Django 5.2.12 on 2026-04-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0037_alter_sede_direccion_alter_sede_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='carta_pdf',
            field=models.FileField(blank=True, help_text='Sube tu carta en formato PDF', null=True, upload_to='cartas_pdf/'),
        ),
        migrations.AddField(
            model_name='sede',
            name='enlace_carta_virtual',
            field=models.URLField(blank=True, help_text='Link a tu menú digital, Canva, Drive o Instagram', max_length=500, null=True),
        ),
    ]
