# Generated by Django 5.2.12 on 2026-04-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0038_sede_carta_pdf_sede_enlace_carta_virtual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('cancelar', 'Cancelar Orden'), ('agregar', 'Agregar Producto'), ('nota', 'Cambiar Nota')], max_length=20)),
                ('detalles_json', models.JSONField(help_text="Datos del cambio: {'producto': id, 'cantidad': 1, 'notas': '...'}")),
                ('estado', models.CharField(choices=[('pendiente', 'Esperando Cocina'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='negocios.orden')),
            ],
        ),
    ]
