# Generated by Django 5.2.12 on 2026-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0039_solicitudcambio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='numero_yape',
            new_name='yape_numero',
        ),
        migrations.AddField(
            model_name='negocio',
            name='culqi_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='culqi_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/logos/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='plin_numero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='plin_qr',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/qrs/plin/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='usa_culqi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='yape_qr',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/qrs/yape/'),
        ),
    ]
