# Generated by Django 5.2.12 on 2026-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0040_rename_numero_yape_negocio_yape_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='carta_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración visual de la carta digital (fuentes, fondos, colores, estilos)'),
        ),
    ]
