# Generated by Django 5.2.12 on 2026-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0041_negocio_carta_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos/'),
        ),
    ]
