# Generated by Django 5.2.12 on 2026-05-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0042_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='dias_atencion',
            field=models.JSONField(blank=True, default=list, help_text="Lista de días. Ej: ['Lunes', 'Martes', ...]"),
        ),
        migrations.AddField(
            model_name='sede',
            name='hora_apertura',
            field=models.TimeField(blank=True, help_text='Hora de apertura', null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='hora_cierre',
            field=models.TimeField(blank=True, help_text='Hora de cierre', null=True),
        ),
    ]
