# Generated by Django 5.2.12 on 2026-05-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0043_sede_dias_atencion_sede_hora_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='bot_cumple_activo',
            field=models.BooleanField(default=False, help_text='¿Activar promoción de cumpleaños con DNI?'),
        ),
        migrations.AddField(
            model_name='sede',
            name='bot_cumple_regalo',
            field=models.CharField(blank=True, help_text='Ej: ¡Te regalamos un postre gratis por tu día!', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='bot_puntos_activos',
            field=models.BooleanField(default=True, help_text='¿El bot gestiona y menciona los puntos?'),
        ),
    ]
