# Generated by Django 5.2.12 on 2026-05-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0044_sede_bot_cumple_activo_sede_bot_cumple_regalo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='bot_max_pedidos_pendientes',
            field=models.IntegerField(default=20, help_text='Límite de pedidos en preparación antes de activar el Modo Cocina Colapsada'),
        ),
    ]
