# Generated by Django 5.2.12 on 2026-05-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0045_sede_bot_max_pedidos_pendientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='bot_cumple_regalo',
        ),
        migrations.AddField(
            model_name='sede',
            name='bot_cumple_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo mínimo en soles para que aplique', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='bot_cumple_productos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs de productos si el tipo es combo. Ej: [1, 5, 8]'),
        ),
        migrations.AddField(
            model_name='sede',
            name='bot_cumple_tipo',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo'), ('combo', 'Combo/Item')], default='porcentaje', help_text='Tipo de beneficio', max_length=20),
        ),
        migrations.AddField(
            model_name='sede',
            name='bot_cumple_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del descuento. Ej: 50 (para 50%) o 20 (para S/ 20)', max_digits=10, null=True),
        ),
    ]
