# Generated by Django 5.2.12 on 2026-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0046_remove_sede_bot_cumple_regalo_sede_bot_cumple_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='bot_cumple_activo',
            field=models.BooleanField(default=False, help_text='¿Activar promoción de cumpleaños?'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='bot_cumple_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo mínimo en soles para que aplique el beneficio.', max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='sede',
            name='bot_cumple_productos',
        ),
        migrations.AlterField(
            model_name='sede',
            name='bot_cumple_tipo',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje de descuento'), ('fijo', 'Monto fijo en soles'), ('combo', 'Combo / Producto gratis')], default='porcentaje', max_length=20),
        ),
        migrations.AlterField(
            model_name='sede',
            name='bot_cumple_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Para 'porcentaje': escribe 20 (= 20%). Para 'fijo': escribe 15 (= S/ 15). Dejar vacío si el tipo es 'combo'.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='dias_atencion',
            field=models.JSONField(blank=True, default=list, help_text='Lista de enteros: [0,1,2] = Lun, Mar, Mié. (0=Lun … 6=Dom)'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='bot_cumple_productos',
            field=models.ManyToManyField(blank=True, help_text="Solo para tipo 'combo': productos que se regalan o descuentan.", related_name='sedes_promo_cumple', to='negocios.producto'),
        ),
    ]
