# Generated by Django 5.2.12 on 2026-05-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0048_orden_subtotal_descuento_recargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariovisibilidad',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='negocios.categoria'),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='precio_especial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='tipo_promo',
            field=models.CharField(choices=[('visibilidad', 'Solo Visibilidad'), ('2x1_producto', '2x1 en Producto'), ('3x2_producto', '3x2 en Producto'), ('2x1_categoria', '2x1 en Categoría'), ('precio_especial', 'Precio Especial')], default='visibilidad', max_length=30),
        ),
        migrations.AlterField(
            model_name='horariovisibilidad',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='negocios.producto'),
        ),
        migrations.AlterField(
            model_name='reglanegocio',
            name='tipo',
            field=models.CharField(choices=[('recargo_llevar', 'Recargo por empaque (Llevar)'), ('delivery_gratis', 'Delivery Gratis por Monto'), ('descuento_dia', 'Descuento por Día Específico'), ('descuento_yape_efectivo', 'Descuento por pagar con Yape/Efectivo'), ('servicio_grupo_grande', 'Recargo 10% por mesa grande (> X personas)'), ('recargo_nocturno', 'Tarifa extra de madrugada')], max_length=30),
        ),
    ]
