# Generated by Django 5.2.12 on 2026-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0049_horariovisibilidad_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariovisibilidad',
            name='rangos_fechas',
            field=models.JSONField(blank=True, default=list, help_text="Ej: [{'inicio': '2026-05-01', 'fin': '2026-05-15'}]"),
        ),
    ]
