# Generated by Django 5.2.12 on 2026-05-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0050_horariovisibilidad_rangos_fechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecombo',
            name='opcion_seleccionada',
            field=models.ForeignKey(blank=True, help_text='Solo si el producto hijo requiere selección', null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.opcionvariacion'),
        ),
        migrations.AddField(
            model_name='componentecombo',
            name='variacion_seleccionada',
            field=models.ForeignKey(blank=True, help_text='Solo si el producto hijo tiene variaciones', null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.variacionproducto'),
        ),
        migrations.CreateModel(
            name='ComboPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='combos_promocionales/')),
                ('rangos_fechas', models.JSONField(default=list, help_text='Lista de rangos de fechas en que aplica el combo')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos_promocionales', to='negocios.negocio')),
            ],
            options={
                'unique_together': {('negocio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ItemComboPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='negocios.combopromocional')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, help_text='Solo si el producto hijo requiere selección', null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.opcionvariacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.producto')),
                ('variacion_seleccionada', models.ForeignKey(blank=True, help_text='Solo si el producto hijo tiene variaciones', null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.variacionproducto')),
            ],
        ),
    ]
