# Generated by Django 5.2.12 on 2026-05-03 20:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0051_componentecombo_opcion_seleccionada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariovisibilidad',
            name='mensaje_fuera_horario',
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='compra_x',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='lleva_y',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='happy_hours', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='porcentaje_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='se_repite_semanalmente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='accion_aplica_a',
            field=models.CharField(choices=[('orden', 'A toda la orden'), ('categoria', 'A una categoría'), ('producto', 'A un producto')], default='orden', max_length=30),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='accion_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.categoria'),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='accion_es_descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='accion_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.producto'),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='condicion_hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='condicion_hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='condicion_metodo_pago',
            field=models.CharField(choices=[('cualquiera', 'Cualquier método'), ('yape', 'Solo Yape'), ('plin', 'Solo Plin'), ('efectivo', 'Solo Efectivo'), ('tarjeta', 'Solo Tarjeta')], default='cualquiera', max_length=30),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='condicion_tipo_orden',
            field=models.CharField(choices=[('cualquiera', 'Cualquier tipo'), ('salon', 'Solo Salón'), ('llevar', 'Solo Para Llevar'), ('delivery', 'Solo Delivery')], default='cualquiera', max_length=30),
        ),
        migrations.AddField(
            model_name='reglanegocio',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='horariovisibilidad',
            name='dias_permitidos',
            field=models.JSONField(default=list, help_text='[0,1,2] = Lun,Mar,Mié'),
        ),
        migrations.AlterField(
            model_name='horariovisibilidad',
            name='rangos_fechas',
            field=models.JSONField(blank=True, default=list, help_text="[{'inicio':'2026-05-01','fin':'2026-05-15'}]"),
        ),
        migrations.AlterField(
            model_name='horariovisibilidad',
            name='tipo_promo',
            field=models.CharField(choices=[('visibilidad', 'Solo Visibilidad (aparece/desaparece)'), ('precio_especial', 'Precio Especial'), ('porcentaje', 'Descuento por Porcentaje'), ('nx_y', 'Compra X Lleva Y')], default='visibilidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='reglanegocio',
            name='tipo',
            field=models.CharField(choices=[('recargo_llevar', 'Recargo por empaque (Llevar)'), ('delivery_gratis', 'Delivery Gratis por Monto'), ('descuento_dia', 'Descuento por Día Específico'), ('descuento_yape_efectivo', 'Descuento por pagar con Yape/Efectivo'), ('servicio_grupo_grande', 'Recargo por mesa grande'), ('recargo_nocturno', 'Tarifa extra de madrugada'), ('personalizada', 'Regla Personalizada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reglanegocio',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
