# Generated by Django 5.2.12 on 2026-05-03 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0052_remove_horariovisibilidad_mensaje_fuera_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariovisibilidad',
            name='opcion_variacion',
            field=models.ForeignKey(blank=True, help_text='Si es null, aplica a todas las presentaciones del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.opcionvariacion'),
        ),
    ]
