# Generated by Django 5.2.12 on 2026-05-04 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0053_horariovisibilidad_opcion_variacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='combopromocional',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Si es null, aplica a todas las sedes del negocio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos_promocionales_sede', to='negocios.sede'),
        ),
        migrations.AddField(
            model_name='horariovisibilidad',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Si es null, aplica a todas las sedes del negocio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='happy_hours', to='negocios.sede'),
        ),
    ]
