# Generated by Django 5.2.12 on 2026-05-13 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0054_combopromocional_sede_horariovisibilidad_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('periodo', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscripcion', to='negocios.negocio')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='negocios.plansaas')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
