# Generated by Django 5.2.12 on 2026-05-13 22:15

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0055_pagosuscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='culqi_webhook_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='culqi_private_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
