# Generated by Django 5.2.12 on 2026-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0056_negocio_culqi_webhook_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='culqi_amount',
            field=models.IntegerField(blank=True, help_text='Monto en céntimos devuelto por Culqi', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='culqi_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='culqi_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('manual', 'Manual')], default='confirmado', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['culqi_order_id'], name='negocios_pa_culqi_o_60fa08_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['culqi_charge_id'], name='negocios_pa_culqi_c_dac1f7_idx'),
        ),
    ]
