# Generated by Django 5.2.12 on 2026-05-14 20:19

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0057_pago_culqi_amount_pago_culqi_charge_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pago',
            name='negocios_pa_culqi_o_60fa08_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='negocios_pa_culqi_c_dac1f7_idx',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='culqi_private_key',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='culqi_public_key',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='culqi_webhook_secret',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='usa_culqi',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='culqi_amount',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='culqi_charge_id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='culqi_order_id',
        ),
        migrations.AddField(
            model_name='negocio',
            name='mp_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mp_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mp_user_id',
            field=models.CharField(blank=True, help_text='ID del Collector/Vendedor en MP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mp_webhook_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Firma secreta para validar webhooks', null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='usa_mercado_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto real cobrado devuelto por MP', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_order_id',
            field=models.CharField(blank=True, help_text='ID de la orden presencial generada', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_payment_id',
            field=models.CharField(blank=True, help_text='ID de la transacción una vez pagada', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['mp_order_id'], name='negocios_pa_mp_orde_721e98_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['mp_payment_id'], name='negocios_pa_mp_paym_680c83_idx'),
        ),
    ]
