# Generated by Django 5.2.12 on 2026-05-15 06:40

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0058_remove_pago_negocios_pa_culqi_o_60fa08_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='mp_access_token',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='mp_public_key',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='mp_user_id',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='mp_webhook_secret',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='usa_mercado_pago',
        ),
        migrations.AddField(
            model_name='negocio',
            name='culqi_private_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='culqi_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='culqi_webhook_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='usa_culqi',
            field=models.BooleanField(default=False),
        ),
    ]
