# Generated by Django 5.2.12 on 2026-05-15 07:02

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0059_remove_negocio_mp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='mp_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mp_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mp_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='mp_webhook_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='usa_mercado_pago',
            field=models.BooleanField(default=False),
        ),
    ]
