# Generated by Django 5.2.12 on 2026-05-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0060_negocio_mp_access_token_negocio_mp_public_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='mp_access_token',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='mp_public_key',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='mp_user_id',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='mp_webhook_secret',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='usa_mercado_pago',
        ),
    ]
