# Generated by Django 5.2.12 on 2026-05-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0061_remove_negocio_mp_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pago',
            name='negocios_pa_mp_orde_721e98_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='negocios_pa_mp_paym_680c83_idx',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='mp_amount',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='mp_order_id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='mp_payment_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='culqi_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='culqi_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='culqi_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('manual', 'Manual'), ('fallido', 'Fallido')], default='confirmado', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['culqi_order_id'], name='negocios_pa_culqi_o_60fa08_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['culqi_charge_id'], name='negocios_pa_culqi_c_dac1f7_idx'),
        ),
    ]
