# Generated by Django 5.2.12 on 2026-05-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0062_remove_pago_negocios_pa_mp_orde_721e98_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin')], default='YAPE', max_length=4)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_seguridad', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='negocios_pa_culqi_o_60fa08_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='negocios_pa_culqi_c_dac1f7_idx',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='culqi_private_key',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='culqi_public_key',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='culqi_webhook_secret',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='usa_culqi',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='culqi_amount',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='culqi_charge_id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='culqi_order_id',
        ),
        migrations.AddField(
            model_name='negocio',
            name='confirmacion_automatica',
            field=models.BooleanField(default=False, help_text='¿El negocio usa la App de Leybrak para auto-validar Yape/Plin?'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='device_token',
            field=models.CharField(blank=True, help_text='Token único que autentica la App Android de este negocio', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('manual', 'Manual')], default='confirmado', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacionpago',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_entrantes', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='notificacion_origen',
            field=models.OneToOneField(blank=True, help_text='Notificación push que validó automáticamente este pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.notificacionpago'),
        ),
        migrations.AddIndex(
            model_name='notificacionpago',
            index=models.Index(fields=['negocio', 'usado', 'fecha_recepcion'], name='negocios_no_negocio_9c5b8d_idx'),
        ),
    ]
