# Generated by Django 5.2.12 on 2026-05-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0063_notificacionpago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to='negocios.empleado'),
        ),
    ]
