# Generated by Django 5.2.12 on 2026-05-29 23:41

from django.db import migrations, models


def normalizar_estado_confirmado(apps, schema_editor):
    """Defensivo: si algún PagoSuscripcion quedó con el valor inválido
    'confirmado' (que nunca estuvo en ESTADO_CHOICES), pasarlo a 'pagado'."""
    PagoSuscripcion = apps.get_model('negocios', 'PagoSuscripcion')
    PagoSuscripcion.objects.filter(estado='confirmado').update(estado='pagado')


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0064_alter_movimientocaja_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosuscripcion',
            name='preference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(
            normalizar_estado_confirmado,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
