# Generated by Django 5.2.12 on 2026-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0065_add_preference_id_fix_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(default='android', max_length=10, unique=True)),
                ('version_code_minima', models.IntegerField(default=1, help_text='Builds con versionCode menor a este se OBLIGAN a actualizar.')),
                ('version_name_ultima', models.CharField(default='1.0.0', help_text='Nombre de la última versión, ej. 1.0.1 (solo para mostrar).', max_length=20)),
                ('apk_url', models.URLField(default='https://pos.leybrak.com/media/leybrak.apk', help_text='URL de descarga del APK más reciente.')),
                ('notas', models.TextField(blank=True, help_text='Qué hay de nuevo (se muestra en la pantalla de actualización).', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si está desactivado, la app no fuerza ninguna actualización.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Versión de la App',
                'verbose_name_plural': 'Versiones de la App',
            },
        ),
    ]
