# Generated by Django 5.2.12 on 2026-06-02 23:50

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0066_version_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='facturacion_emision',
            field=models.CharField(choices=[('desactivado', 'Desactivado'), ('opcional', 'Opcional (botón al cobrar)'), ('automatico', 'Automático (toda venta)')], default='desactivado', help_text='Cómo se emiten comprobantes SUNAT al cobrar.', max_length=12),
        ),
        migrations.AddField(
            model_name='negocio',
            name='facturacion_entorno',
            field=models.CharField(choices=[('demo', 'Demo (pruebas)'), ('produccion', 'Producción')], default='demo', help_text='Qué credenciales de Nubefact usar.', max_length=12),
        ),
        migrations.AddField(
            model_name='negocio',
            name='facturacion_ruta',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='URL/RUTA de la cuenta Nubefact del negocio (solo producción).', null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='facturacion_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Token de la cuenta Nubefact del negocio (solo producción).', null=True),
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta de venta')], max_length=10)),
                ('serie', models.CharField(max_length=4)),
                ('numero', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('emisor_ruc', models.CharField(max_length=11)),
                ('emisor_razon_social', models.CharField(max_length=255)),
                ('receptor_tipo_doc', models.CharField(default='-', max_length=1)),
                ('receptor_num_doc', models.CharField(blank=True, max_length=15)),
                ('receptor_denominacion', models.CharField(default='Cliente varios', max_length=255)),
                ('receptor_direccion', models.CharField(blank=True, max_length=255)),
                ('receptor_email', models.EmailField(blank=True, max_length=254)),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_sunat', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado por SUNAT'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=12)),
                ('aceptado_por_sunat', models.BooleanField(default=False)),
                ('enlace', models.URLField(blank=True)),
                ('enlace_pdf', models.URLField(blank=True)),
                ('codigo_hash', models.CharField(blank=True, max_length=128)),
                ('sunat_description', models.TextField(blank=True)),
                ('payload_enviado', models.JSONField(blank=True, default=dict)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='negocios.negocio')),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobante', to='negocios.orden')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.sede')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['negocio', 'estado_sunat'], name='negocios_co_negocio_1f9e5a_idx')],
                'unique_together': {('negocio', 'tipo', 'serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SerieComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta')], max_length=10)),
                ('serie', models.CharField(max_length=4)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_comprobante', to='negocios.negocio')),
            ],
            options={
                'unique_together': {('negocio', 'tipo', 'serie')},
            },
        ),
    ]
