# Generated by Django 5.2.12 on 2026-06-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0067_facturacion_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='facturacion_serie_boleta',
            field=models.CharField(default='B001', help_text='Serie de boletas registrada en tu cuenta Nubefact (ej. B001, BBB1).', max_length=4),
        ),
        migrations.AddField(
            model_name='negocio',
            name='facturacion_serie_factura',
            field=models.CharField(default='F001', help_text='Serie de facturas registrada en tu cuenta Nubefact (ej. F001, FFF1).', max_length=4),
        ),
    ]
