# Generated by Django 5.2.12 on 2026-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0068_facturacion_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='bot_emojis',
            field=models.CharField(blank=True, default='', help_text="Emojis que puede usar (ej. 🍔🔥😋) o 'ninguno' para que no use.", max_length=255),
        ),
        migrations.AddField(
            model_name='negocio',
            name='bot_instrucciones',
            field=models.TextField(blank=True, default='', help_text="Reglas/instrucciones extra para el bot (ej. 'Siempre ofrece el combo del día')."),
        ),
        migrations.AddField(
            model_name='negocio',
            name='bot_nombre',
            field=models.CharField(blank=True, default='', help_text="Nombre del asistente, ej. 'Bravito'. Vacío = sin nombre propio.", max_length=50),
        ),
        migrations.AddField(
            model_name='negocio',
            name='bot_personalidad',
            field=models.TextField(blank=True, default='', help_text='Cómo habla el bot: tono, trato (tú/usted), jerga, qué tan formal o divertido.'),
        ),
    ]
