# Generated by Django 5.2.12 on 2026-06-09 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0069_negocio_bot_emojis_negocio_bot_instrucciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de la historia.', upload_to='historias/')),
                ('texto', models.TextField(blank=True, default='', help_text='Texto/caption de la historia (opcional).')),
                ('fecha_programada', models.DateTimeField(help_text='Cuándo debe publicarse.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('publicada', 'Publicada'), ('error', 'Error'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(help_text='Sede cuya línea de WhatsApp publica la historia.', on_delete=django.db.models.deletion.CASCADE, related_name='historias_programadas', to='negocios.sede')),
            ],
            options={
                'verbose_name': 'Historia programada',
                'verbose_name_plural': 'Historias programadas',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
