# Generated by Django 5.2.12 on 2026-06-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0070_historiaprogramada'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaprogramada',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, help_text="Días para 'semanal': lista 0=Lun … 6=Dom."),
        ),
        migrations.AddField(
            model_name='historiaprogramada',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Hasta qué día se repite (opcional, vacío=indefinido).', null=True),
        ),
        migrations.AddField(
            model_name='historiaprogramada',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Desde qué día se repite (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='historiaprogramada',
            name='frecuencia',
            field=models.CharField(choices=[('unica', 'Una vez'), ('diaria', 'Todos los días'), ('semanal', 'Días de la semana')], default='unica', max_length=10),
        ),
        migrations.AddField(
            model_name='historiaprogramada',
            name='hora',
            field=models.TimeField(blank=True, help_text='Hora del día a publicar (recurrentes).', null=True),
        ),
        migrations.AddField(
            model_name='historiaprogramada',
            name='ultima_publicacion_dia',
            field=models.DateField(blank=True, help_text='Último día que se publicó (anti-duplicado).', null=True),
        ),
        migrations.AlterField(
            model_name='historiaprogramada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente / Activa'), ('publicada', 'Publicada'), ('error', 'Error'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=12),
        ),
        migrations.AlterField(
            model_name='historiaprogramada',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, help_text="Cuándo publicar (solo 'una vez').", null=True),
        ),
    ]
