# Generated by Django 5.2.12 on 2026-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0071_historiaprogramada_dias_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='bot_ingreso_automatico',
            field=models.BooleanField(default=True, help_text="¿Los pedidos del bot pasan directo a cocina ('preparando')? Si está OFF, quedan 'pendiente' para revisión humana."),
        ),
    ]
