# Generated by Django 5.2.12 on 2026-06-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0072_sede_bot_ingreso_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='bot_reglas',
            field=models.JSONField(blank=True, default=list, help_text="Lista de reglas, ej. ['Siempre ofrece el combo del día', 'Nunca prometas descuentos']."),
        ),
        migrations.AddField(
            model_name='negocio',
            name='bot_tono',
            field=models.JSONField(blank=True, default=list, help_text="Presets de tono elegidos, ej. ['amable','rapido']."),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='bot_emojis',
            field=models.CharField(blank=True, default='', help_text='Emojis que puede usar (ej. 🍔🔥😋). Vacío = pocos/ninguno.', max_length=255),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='bot_instrucciones',
            field=models.TextField(blank=True, default='', help_text='(Legado) Instrucciones libres.'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='bot_personalidad',
            field=models.TextField(blank=True, default='', help_text='Nota de personalidad extra (opcional).'),
        ),
    ]
