# Generated by Django 5.2.12 on 2026-06-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0073_negocio_bot_reglas_negocio_bot_tono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('calificacion', models.IntegerField(blank=True, help_text='1 a 5 estrellas (opcional).', null=True)),
                ('comentario', models.TextField(blank=True, default='')),
                ('visto', models.BooleanField(default=False, help_text='¿El dueño ya lo revisó?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='negocios.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='negocios.negocio')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='negocios.orden')),
            ],
            options={
                'verbose_name': 'Feedback de cliente',
                'verbose_name_plural': 'Feedbacks de clientes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
