# Generated by Django 5.2.12 on 2026-06-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0074_feedbackcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='puntos_activo',
            field=models.BooleanField(default=False, help_text='¿El negocio usa sistema de puntos? Controla si el bot los menciona y permite canjear.'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='puntos_canje_minimo',
            field=models.IntegerField(default=100, help_text='Puntos mínimos para poder canjear.'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='puntos_por_sol',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Puntos que gana el cliente por cada S/1 gastado (ej. 1 = 1 punto por sol).', max_digits=6),
        ),
        migrations.AddField(
            model_name='negocio',
            name='puntos_valor_soles',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Valor en S/ de cada punto al canjear (ej. 0.10 → 100 pts = S/10 de descuento).', max_digits=6),
        ),
        migrations.CreateModel(
            name='CanjePuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(help_text='Puntos canjeados.')),
                ('valor_soles', models.DecimalField(decimal_places=2, help_text='Descuento en S/ otorgado.', max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes', to='negocios.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes_puntos', to='negocios.negocio')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes', to='negocios.orden')),
            ],
            options={
                'verbose_name': 'Canje de puntos',
                'verbose_name_plural': 'Canjes de puntos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
