# Generated by Django 5.2.12 on 2026-06-10 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0075_negocio_puntos_activo_negocio_puntos_canje_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen del sticker (idealmente cuadrada / webp).', upload_to='stickers/')),
                ('contexto', models.CharField(choices=[('saludo', 'Saludo / bienvenida'), ('pedido_confirmado', 'Pedido enviado a cocina'), ('delivery_camino', 'Delivery en camino'), ('agradecimiento', 'Agradecimiento'), ('despedida', 'Despedida'), ('general', 'General / comodín')], default='general', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Sticker del bot',
                'verbose_name_plural': 'Stickers del bot',
                'ordering': ['contexto', '-creado_en'],
            },
        ),
    ]
