# Generated by Django 5.2.12 on 2026-06-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0076_botsticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='puntos_otorgados',
            field=models.BooleanField(default=False),
        ),
    ]
