# Generated by Django 5.2.12 on 2026-06-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0077_orden_puntos_otorgados'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_delivery',
            field=models.CharField(choices=[('pendiente', 'Sin asignar'), ('asignado', 'Asignado'), ('en_camino', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=12),
        ),
        migrations.AddField(
            model_name='orden',
            name='repartidor',
            field=models.ForeignKey(blank=True, help_text='Repartidor que tomó el pedido de delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='negocios.empleado'),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_repartir',
            field=models.BooleanField(default=False, help_text='¿Es repartidor? Ve la pantalla de reparto.'),
        ),
    ]
